# See https://sw.kovidgoyal.net/kitty/conf.html
font_family Jetbrains Mono NerdFont
symbol_map U+0025 U+0025 FiraCode Nerd Font
font_size 14

# Shell integration is sourced and configured manually
shell_integration no-rc

hide_window_decorations no

enable_audio_bell 0

cursor_trail 1

window_padding_width 8
dynamic_padding yes

confirm_os_window_close 0

# Basic Colors
foreground              #abb2bf
background              #1d2021
selection_foreground    #ebdbb2
selection_background    #665c54
background_opacity      1

# Cursor Colors
cursor                  #fabd2f
cursor_text_color       #282828

# URL Underline Color
url_color               #fabd2f

# Kitty Window Border Colors
active_border_color     #e06c75
inactive_border_color   #5c6370
bell_border_color       #fabd2f

# Tab Bar Colors
active_tab_foreground   #282828
active_tab_background   #fabd2f
inactive_tab_foreground #abb2bf
inactive_tab_background #3c3836
tab_bar_background      #282828

# Marked Text Colors
mark1_foreground #282828
mark1_background #e06c75
mark2_foreground #282828
mark2_background #fabd2f
mark3_foreground #282828
mark3_background #98c379

# 16 Terminal Colors

# Black
color0 #282828
color8 #5c6370

# Red
color1 #e06c75
color9 #e06c75

# Green
color2 #98c379
color10 #98c379

# Yellow
color3 #e5c07b
color11 #e5c07b

# Blue
color4 #61afef
color12 #61afef

# Magenta
color5 #c678dd
color13 #c678dd

# Cyan
color6 #56b6c2
color14 #56b6c2

# White
color7 #abb2bf
color15 #ffffff
