-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    general = {
        snap = {
            border_overlap = true,
            enabled = false,
        },
    },
    misc = {
        vrr = 1,
    },
})

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = false,
})
